// db/exerciseSeed.ts
// Mirrors AscendFit/Resources/exercise_seed.json exactly — same 20 exercises,
// same stat weights, same contraindications.

import type { ExerciseDefinition } from '../types';

export const EXERCISE_SEED: ExerciseDefinition[] = [
  {
    id: 'bench_press', name: 'Barbell Bench Press', category: 'strength',
    primaryMuscleGroups: ['chest', 'shoulders', 'triceps'],
    equipmentRequired: ['barbellRack', 'fullGym'],
    statWeights: { strength: 0.7, endurance: 0.05, discipline: 0.1, vitality: 0.15 },
    difficultyTier: 3,
    instructions: 'Lie on a flat bench, lower the bar to mid-chest with control, press back to lockout.',
    contraindicatedFor: ['shoulder'],
  },
  {
    id: 'incline_dumbbell_press', name: 'Incline Dumbbell Press', category: 'strength',
    primaryMuscleGroups: ['chest', 'shoulders'],
    equipmentRequired: ['dumbbells', 'fullGym'],
    statWeights: { strength: 0.65, endurance: 0.05, discipline: 0.1, vitality: 0.2 },
    difficultyTier: 2,
    instructions: 'Set bench to 30-45 degrees. Press dumbbells from shoulder height to lockout.',
    contraindicatedFor: ['shoulder'],
  },
  {
    id: 'barbell_back_squat', name: 'Barbell Back Squat', category: 'strength',
    primaryMuscleGroups: ['quads', 'glutes', 'hamstrings'],
    equipmentRequired: ['barbellRack', 'fullGym'],
    statWeights: { strength: 0.75, endurance: 0.1, agility: 0.05, discipline: 0.1 },
    difficultyTier: 4,
    instructions: 'Bar on upper back, squat until hips are below knees, drive back up through heels.',
    contraindicatedFor: ['knee', 'lower_back'],
  },
  {
    id: 'goblet_squat', name: 'Goblet Squat', category: 'strength',
    primaryMuscleGroups: ['quads', 'glutes'],
    equipmentRequired: ['dumbbells', 'none'],
    statWeights: { strength: 0.5, endurance: 0.15, agility: 0.1, discipline: 0.1, vitality: 0.15 },
    difficultyTier: 1,
    instructions: 'Hold a dumbbell at chest height, squat down keeping torso upright, drive back up.',
    contraindicatedFor: ['knee'],
  },
  {
    id: 'deadlift', name: 'Barbell Deadlift', category: 'strength',
    primaryMuscleGroups: ['back', 'hamstrings', 'glutes'],
    equipmentRequired: ['barbellRack', 'fullGym'],
    statWeights: { strength: 0.8, endurance: 0.05, discipline: 0.15 },
    difficultyTier: 5,
    instructions: 'Hinge at the hips, grip the bar outside your knees, drive through the floor to stand tall.',
    contraindicatedFor: ['lower_back'],
  },
  {
    id: 'lat_pulldown', name: 'Lat Pulldown', category: 'strength',
    primaryMuscleGroups: ['back', 'biceps'],
    equipmentRequired: ['fullGym'],
    statWeights: { strength: 0.6, endurance: 0.1, discipline: 0.1, vitality: 0.2 },
    difficultyTier: 2,
    instructions: 'Pull the bar down to upper chest, squeezing shoulder blades together, control the return.',
    contraindicatedFor: ['shoulder'],
  },
  {
    id: 'barbell_row', name: 'Barbell Row', category: 'strength',
    primaryMuscleGroups: ['back', 'biceps'],
    equipmentRequired: ['barbellRack', 'fullGym'],
    statWeights: { strength: 0.65, endurance: 0.1, discipline: 0.15, vitality: 0.1 },
    difficultyTier: 3,
    instructions: 'Hinge forward with a flat back, row the bar to your lower ribs, lower with control.',
    contraindicatedFor: ['lower_back'],
  },
  {
    id: 'overhead_press', name: 'Overhead Press', category: 'strength',
    primaryMuscleGroups: ['shoulders', 'triceps'],
    equipmentRequired: ['barbellRack', 'dumbbells', 'fullGym'],
    statWeights: { strength: 0.7, endurance: 0.05, discipline: 0.1, vitality: 0.15 },
    difficultyTier: 3,
    instructions: 'Press the bar/dumbbells from shoulder height straight overhead to lockout.',
    contraindicatedFor: ['shoulder'],
  },
  {
    id: 'push_up', name: 'Push-Up', category: 'bodyweight',
    primaryMuscleGroups: ['chest', 'shoulders', 'triceps'],
    equipmentRequired: ['none'],
    statWeights: { strength: 0.5, endurance: 0.15, agility: 0.05, discipline: 0.1, vitality: 0.2 },
    difficultyTier: 1,
    instructions: 'Hands under shoulders, lower chest to the floor, press back up keeping core tight.',
    contraindicatedFor: ['shoulder'],
  },
  {
    id: 'pull_up', name: 'Pull-Up', category: 'bodyweight',
    primaryMuscleGroups: ['back', 'biceps'],
    equipmentRequired: ['none'],
    statWeights: { strength: 0.65, endurance: 0.1, agility: 0.05, discipline: 0.15, vitality: 0.05 },
    difficultyTier: 4,
    instructions: 'Hang from a bar, pull chin above the bar, lower with control.',
    contraindicatedFor: ['shoulder'],
  },
  {
    id: 'bodyweight_lunge', name: 'Bodyweight Lunge', category: 'bodyweight',
    primaryMuscleGroups: ['quads', 'glutes', 'hamstrings'],
    equipmentRequired: ['none'],
    statWeights: { strength: 0.4, endurance: 0.2, agility: 0.15, discipline: 0.1, vitality: 0.15 },
    difficultyTier: 1,
    instructions: 'Step forward into a lunge, knee tracking over toes, push back to standing.',
    contraindicatedFor: ['knee'],
  },
  {
    id: 'plank', name: 'Plank Hold', category: 'bodyweight',
    primaryMuscleGroups: ['core'],
    equipmentRequired: ['none'],
    statWeights: { strength: 0.2, endurance: 0.2, discipline: 0.4, vitality: 0.2 },
    difficultyTier: 1,
    instructions: 'Forearms on the floor, body in a straight line, hold while breathing steadily.',
    contraindicatedFor: ['lower_back'],
  },
  {
    id: 'burpee', name: 'Burpee', category: 'hiit',
    primaryMuscleGroups: ['full_body'],
    equipmentRequired: ['none'],
    statWeights: { strength: 0.2, endurance: 0.35, agility: 0.25, discipline: 0.1, vitality: 0.1 },
    difficultyTier: 3,
    instructions: 'Drop to a plank, push up, jump feet to hands, explode upward into a jump.',
    contraindicatedFor: ['knee', 'shoulder'],
  },
  {
    id: 'jumping_jacks', name: 'Jumping Jacks', category: 'cardio',
    primaryMuscleGroups: ['full_body'],
    equipmentRequired: ['none'],
    statWeights: { endurance: 0.4, agility: 0.3, discipline: 0.1, vitality: 0.2 },
    difficultyTier: 1,
    instructions: 'Jump while raising arms overhead and spreading feet, return to start, repeat.',
    contraindicatedFor: [],
  },
  {
    id: 'stationary_bike', name: 'Stationary Bike', category: 'cardio',
    primaryMuscleGroups: ['quads', 'hamstrings'],
    equipmentRequired: ['cardioMachine'],
    statWeights: { strength: 0.05, endurance: 0.55, discipline: 0.1, recovery: 0.1, vitality: 0.2 },
    difficultyTier: 1,
    instructions: 'Maintain a steady cadence at a challenging-but-sustainable resistance for the full duration.',
    contraindicatedFor: ['knee'],
  },
  {
    id: 'rowing_machine', name: 'Rowing Machine', category: 'cardio',
    primaryMuscleGroups: ['back', 'legs', 'core'],
    equipmentRequired: ['cardioMachine'],
    statWeights: { strength: 0.15, endurance: 0.5, discipline: 0.1, recovery: 0.05, vitality: 0.2 },
    difficultyTier: 2,
    instructions: 'Drive with the legs, lean back slightly, pull the handle to the lower ribs, reverse smoothly.',
    contraindicatedFor: ['lower_back'],
  },
  {
    id: 'brisk_walk', name: 'Brisk Walk', category: 'walking',
    primaryMuscleGroups: ['quads', 'hamstrings', 'calves'],
    equipmentRequired: ['none'],
    statWeights: { endurance: 0.3, agility: 0.05, discipline: 0.15, recovery: 0.2, vitality: 0.3 },
    difficultyTier: 1,
    instructions: 'Walk at a pace that elevates your heart rate while remaining able to hold a conversation.',
    contraindicatedFor: [],
  },
  {
    id: 'incline_walk', name: 'Incline Treadmill Walk', category: 'walking',
    primaryMuscleGroups: ['glutes', 'calves'],
    equipmentRequired: ['cardioMachine'],
    statWeights: { strength: 0.05, endurance: 0.35, discipline: 0.1, recovery: 0.15, vitality: 0.35 },
    difficultyTier: 2,
    instructions: 'Set a moderate incline, walk at a steady pace without holding the rails.',
    contraindicatedFor: ['knee'],
  },
  {
    id: 'cat_cow_stretch', name: 'Cat-Cow Stretch', category: 'mobility',
    primaryMuscleGroups: ['spine', 'core'],
    equipmentRequired: ['none'],
    statWeights: { agility: 0.2, discipline: 0.1, recovery: 0.5, vitality: 0.2 },
    difficultyTier: 1,
    instructions: 'On hands and knees, alternate arching and rounding the spine slowly with your breath.',
    contraindicatedFor: [],
  },
  {
    id: 'hip_flexor_stretch', name: 'Hip Flexor Stretch', category: 'mobility',
    primaryMuscleGroups: ['hips'],
    equipmentRequired: ['none'],
    statWeights: { agility: 0.25, discipline: 0.1, recovery: 0.45, vitality: 0.2 },
    difficultyTier: 1,
    instructions: 'Kneel in a lunge position, gently press hips forward, hold and switch sides.',
    contraindicatedFor: ['knee'],
  },
];
